---

- hosts: acl_net
  gather_facts: no
  debugger: on_failed

# vars_prompt:

#   - name: ansible_user
#     prompt: Whats is your username ?
#     private: no

#   - name: ansible_ssh_pass
#     prompt: Enter password
#     private: yes

  tasks:

    - name: import set_snmp role
      import_role:
        name: cellcom.deploy.acl
