---

- hosts: software_upgrade_net
  gather_facts: no
  ignore_unreachable: yes
  ignore_errors: no
  debugger: on_failed

# vars_prompt:
#
#   - name: ansible_user
#     prompt: Whats is your username ?
#     private: no
#
#   - name: ansible_ssh_pass
#     prompt: Enter password
#     private: yes

  tasks:
    - name: import software_upgrade role
      import_role:
        name: cellcom.deploy.software_upgrade
