apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-storage-pv-claim
  namespace: filebrowser
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: "" # set empty in order to choose pv by name.
  volumeName: filebrowser-storage-pv
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-database-pv-claim
  namespace: filebrowser
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "" # set empty in order to choose pv by name.
  volumeName: filebrowser-database-pv
