apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-storage-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/docs/files"
  
---  
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-database-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/docs/database.db"
