apiVersion: v1
kind: Service
metadata:
  name: filebrowser-service-external-port
  namespace: filebrowser-3
spec:
  type: NodePort
  ports:
  - nodePort: 30031
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: filebrowser
