---
# tasks file for set_snmp

#- name: import vars from playbook path
#  include_vars:
#    dir: "{{ playbook_dir }}/vars/{{ role_name }}"
#    ignore_unknown_extensions: True
#    extensions:
#      - 'yaml'
#      - 'yml'

- name: import ios-xr task
  import_tasks: ios_xr_device.yml
  when: ansible_network_os == "cisco.iosxr.iosxr"
