---
# tasks file for software_upgrade

- name: import vars from playbook path
  include_vars:
    dir: "{{ playbook_dir }}/vars/{{ role_name }}"
    ignore_unknown_extensions: True
    extensions:
      - 'yaml'
      - 'yml'
  tags: [image, smu, bios]


- name: import ios_xr
  import_tasks: ios_xr.yml
  when: ansible_network_os == "cisco.iosxr.iosxr"
