---

- name: block of tasks that relate to isis nsap address
  block:
    - name: configure nsap address from loopback0
      cellcom.configurator.isis_nsap_cal:
        loopback: "{{ item['ip_loopback0'] }}"
      register: isis_nsap_id_result
    
    - name: setting isis_nsap_id parameter
      set_fact:
        isis_nsap_id: "{{ isis_nsap_id_result['result'] }}"

#- name: print isis_nsap_id for debugging
#  ansible.builtin.debug:
#    msg: "isis_nsap_id result ==> {{ isis_nsap_id }}"

- name: set domain_ring_id hostname
  set_fact:
    domain_ring_hostname: "{{ item['hostname'] }}"

- name: derive domain_ring_id from hostname
  import_tasks: set_domain_ring_id.yml

- name: set metrics to ports 28 and 29
  import_tasks: set_metrics_to_ports.yml

- name: set priorities to ports 28 and 29
  import_tasks: set_priority_to_ports.yml

- name: define output path
  import_tasks: define_output_path.yml

- name: export template config file to "{{ playbook_dir }}/{{ output_config_path }}"
  ansible.builtin.template:
    src: "files/540_config_template.j2"
    dest: "{{ playbook_dir }}/{{ output_config_path }}/{{ item['hostname'] }}.txt"
