---
# tasks file for prepare_configs

- name: import vars from playbook path
  include_vars:
    dir: "{{ playbook_dir }}/vars/{{ role_name }}"
    ignore_unknown_extensions: True
    extensions:
      - 'yaml'
      - 'yml'

- name: prepare access configurations
  include_tasks: prepare_access_configs.yml
  when: "'access' is defined"
  loop: "{{ access }}"

- name: prepare aggregate configurations
  include_tasks: prepare_aggregate_configs.yml
  when: "'aggregate' is defined"
  loop: "{{ aggregate }}"
