apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
    - image: docker.io/library/ubuntu
      name: ubuntu-debug
      command: ['/bin/bash', '-c']
      args: ["apt update && apt install -y iputils-ping dnsutils && sleep 3600"]
